services:
  postgres:
    image: postgres:16-alpine
    container_name: bug-report-web-postgres
    environment:
      POSTGRES_USER: bugreport
      POSTGRES_PASSWORD: bugreport
      POSTGRES_DB: bugreport
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
