ALTER TYPE "BugActivityType" ADD VALUE 'OWNER_CLAIMED';
ALTER TYPE "BugActivityType" ADD VALUE 'OWNER_DELEGATED';
ALTER TYPE "BugActivityType" ADD VALUE 'OWNER_REVOKED';
ALTER TYPE "BugActivityType" ADD VALUE 'RELATED_JOINED';
ALTER TYPE "BugActivityType" ADD VALUE 'RELATED_ADDED';
ALTER TYPE "BugActivityType" ADD VALUE 'RELATED_REMOVED';
